Minor shell and README updates

diff --git a/dockint b/dockint
--- a/dockint
+++ b/dockint
@@ -12,6 +12,7 @@ usage=\
     The dockint environment is mounted as your home directory inside the container
 
     1. init [directory] : turn the specified directory (defaults to current directory) into a dockint environment
+       - The dockint environment can then be modified before building
     2. from <base_image> : build the docker container in the current directory, deriving it from the specified base image
        - This will initialize a =.dockint= environment in the current directory if it has not yet been initialized
     3. activate [directory] : Start working inside the docker container connected with the current dockint environment
@@ -29,7 +30,7 @@ usage=\
 
 # The base dockerfile
 dockerfile=\
-'ARG BASE
+'ARG BASE=scratch
 FROM $BASE
 
 # Make Xwindows work with the native x server and qt
@@ -55,7 +56,7 @@ WORKDIR /home/$UNAME'
 
 
 # determine if we need to use sudo when calling docker
-if groups $USER | grep -q docker;
+if groups "$USER" | grep -q docker;
 then
     DOCKER=docker
 else
@@ -92,18 +93,18 @@ docker_activate() {
     fi
 
     # If the container is not running
-    container=$(cat $dockintdir/container_name)
-    if [ -z $($DOCKER ps -q --filter "name=$container" --filter "status=running") ];
+    container="$(cat "$dockintdir"/container_name)"
+    if [ -z "$($DOCKER ps -q --filter "name=$container" --filter "status=running")" ];
     then
         # if the container does not exist run it (which makes it exist and starts it
-        if [ -z $($DOCKER ps -q --filter "name=$container") ];
+        if [ -z "$($DOCKER ps -q --filter "name=$container")" ];
         then
             # run docker, giving it access to the specified devices and X windows
             # the cap-add and security-opt lets me use gdb to debug ros nodes
             xhost +local:root
-            $DOCKER run -itd  --name "$(cat $dockintdir/container_name)" \
+            if ! $DOCKER run -itd  --name "$(cat "$dockintdir"/container_name)" \
                 --hostname "$HOST" \
-                -v $homedir:/home/$1 \
+                -v "$homedir":/home/"$1" \
                 -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 \
                 -v /etc/machine-id:/etc/machine-id \
                 -v /var/run/dbus:/var/run/dbus \
@@ -113,27 +114,26 @@ docker_activate() {
                 --privileged \
                 --network=host \
                 -v /dev/:/dev \
-                -v $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
-                -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
-                "$(cat $dockintdir/image_name)"
-
-            if [ $? -ne 0 ]; then
+                -v "$XDG_RUNTIME_DIR":"$XDG_RUNTIME_DIR" \
+                -e XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
+                "$(cat "$dockintdir"/image_name)";
+            then
                 echo "Failed to run docker container $container."
                 exit 1
             fi
          else
                #the container exists it just needs to be started
-             $DOCKER start $container
-             if [ $? -ne 0 ]; then
+             if ! $DOCKER start "$container";
+             then
                  echo "Failed to start docker container $container."
                  exit 1
              fi
         fi
-
     fi
+
     # At this point the container is running, so execute bash
-    $DOCKER exec -it -u $1 $container /bin/bash
-    if [ $? -ne 0 ]; then
+    if ! $DOCKER exec -it -u "$1" "$container" /bin/bash;
+    then
         echo "Failed to exec /bin/bash in docker container $container."
         exit 1
     fi
@@ -150,7 +150,7 @@ init_dockint_environment() {
         dockintdir="$2/.dockint"
     fi
     mkdir -p "$dockintdir"
-    printf "$dockerfile" > "$dockintdir/Dockerfile"
+    printf '%s' "$dockerfile" > "$dockintdir/Dockerfile"
     cp /etc/group "$dockintdir"
     cp /etc/passwd "$dockintdir"
 }
@@ -173,11 +173,16 @@ docker_build_image() {
     image_tag=${name}_img
     container=${name}_container
     cd .dockint
-    echo $image_tag > image_name
-    echo $container > container_name
-    $DOCKER build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg UNAME=$USER --build-arg BASE=$base_image --tag "$image_tag" .
-    if [ $? -ne 0 ]; then
-        echo "Failed to create docker image $image"
+    echo "$image_tag" > image_name
+    echo "$container" > container_name
+    if ! $DOCKER build \
+         --build-arg UID="$(id -u)" \
+         --build-arg GID="$(id -g)" \
+         --build-arg UNAME="$USER" \
+         --build-arg BASE="$base_image" \
+         --tag "$image_tag" .;
+    then
+        echo "Failed to create docker image $base_image"
         exit 1
     fi
 }
@@ -210,30 +215,30 @@ docker_remove() {
         exit 1
     fi
 
-    container=$(cat $dockintdir/container_name)
-    $DOCKER stop $container
-    $DOCKER rm $container
+    container=$(cat "$dockintdir"/container_name)
+    $DOCKER stop "$container"
+    $DOCKER rm "$container"
 }
 
 case $1 in
     init)
-        init_dockint_environment $2
+        init_dockint_environment "$2"
         exit 0
         ;;
     from)
-        docker_build_image $2
+        docker_build_image "$2"
         exit 0
         ;;
     activate)
-        docker_activate $USER $2
+        docker_activate "$USER" "$2"
         exit 0
         ;;
     root)
-        docker_activate root $2
+        docker_activate root "$2"
         exit 0
         ;;
     reset)
-        docker_remove $2
+        docker_remove "$2"
         exit 0
         ;;
     *)
